name: compgen
channels:
  - conda-forge
  - defaults
dependencies:
  - python=2.7
  - anaconda
  - cython
  - numpy
  - scipy
  - pandas
  - seaborn
  - ipywidgets
  - tqdm
  - scikit-learn
  - pymc3
  - pip:
    - cython
